# = ProtocolSupportPocketStuff =
#  Enable / Disable / Configure
#   pocket-assisting features
#
# = Skins =
# PCtoPE      - Enables the caching and sending of Java edition skins to bedrock players.
# PEtoPC      - Enables the uploading of skins to mineskin.net to fake PE skins for PC players.
# cache-size  - Determines the maximum cachesize. The cache is needed for skins but can impact memory.
#               It is best to set it to roughly the size of your regular playerbase.
#               Unless skins are disabled do not set the size to 0!
# cache-rate  - Determines how long skins are cached. This will not impact skin change,
#               but determines how fast (in hours) the skins in the cache are cleaned 
#               and thus also need to be redownloaded if they are to be used again.
#               Unless skins are disabled do not set the rate to 0!
#
# = Pocket Packs =
# force-resources - Forces packs to the client, if the client rejects the resource pack, it will be kicked
# behavior-packs  - List with the file names of the resource packs
# resource-packs  - List with the file names of the resource packs
#
# (Behavior Packs and Resource Packs)
# Note: The packs are applied from the bottom to the top (in the same way PC/PE resource packs are applied).
# The last pack is applied first, then the next one, then the next one, and so on.
# This means the first pack in the list will override all changes from the subsequent packs
# !Packs must be added to ./plugins/ProtocolSupportPocketStuff/pocketpacks!
#
# = Hacks =
# dimensions  - Enables using bukkit to fake dimension switching for pocket players.
# holograms   - Enables experimental caching and "armor stand to player" replacement to support holograms for PE players.
# itemframes  - Enables experimental caching and mucking with packets to support itemframes for PE players.
# teams       - Enables experimental caching and mucking with packets to support team prefix/suffixes for PE players.
# bossbars    - Enables experimental caching and mucking with packets to boss bars for PE players.
#
# !Do not change the config-version unless you know what you are doing!

logging:
 disable-colors: false
 enable-debug: false
skins:
 PCtoPE: true
 PEtoPC: true
 cache-size: 250
 cache-rate: 24
pocketpacks:
 force-resources: false
 behavior-packs: []
 resource-packs: []
hacks: 
 dimensions: true
 holograms: true
 itemframes: false
 teams: false
 bossbars: false
config-version: 1
